apiVersion: v1
kind: Service
metadata:
  name: "webserver-service"
  namespace: default
spec:
  selector:
    app: "webserver"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort 